VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 1  'vbDataSource
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "RetCupom"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public Cupom As String
Public Valor As String
Public CodBandeira As String
Public CodRede As String
Public CodAutorizacao As String
Public Nsu As String
Public Parcelas As String
Public TxServico As String
Public BinCartao As String
Public UltimosDigitos As String
Public Cnpj As String
Public Cliente As String
Public NsuRede As String
Public VenctoCartao As String
Public Comprovante As String
